apiVersion: v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: .env
          volumes:
            - name: hello-world-config
              configMap:
                name: hello-world-config
          env:
            - name: POSTGRES_PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: postgres-password
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: 80
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelay }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
