#Defaults

replicaCount: 2

image:
  repository: https://ghcr.io

postgresPassword: "password"

configMap:
  DBUSER: prod-user
  DBNAME: fruit
  DBPORT: 5432
  DBHOST: localhost

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

probes:
  liveness:
    path: "/health"
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: "/health"
    initialDelaySeconds: 10
    periodSeconds: 10